urls_short/urls.py
from django.conf.urls import url

from urls_short import views

urlpatterns = [
    url(r'^$', views.urls_list, name='index'),
    #url(r'^add/$', views.URLCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.remove, name='remove'),
    url(r'^(?P<pk>\d+)/', views.detail, name='detail'),
    url(r'^/(?P<pk>\d+)/$', views.urls_list, name='index'),
    url(r'^edit/(?P<pk>\d+)/$', views.edit, name='edit'),
    url(r'^share/(?P<pk>\d+)/$', views.share, name='share'),
    ]

web_url/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from web_url import views

urlpatterns = [
    # Examples:
    # url(r'^$', 'web_url.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^$', views.url, name="index"),
    url(r'^urls/', include('urls_short.urls', namespace="urls_short")),
    url(r'^admin/', include(admin.site.urls)),
  #  url(r'^$', views.urls_list, name="index"),
 #   url(r'^remove/(?P<pk>\d+)/$', views.remove, name='remove'),
]

urls_short/models.py
from django.db import models
from django.contrib.auth.models import User

class URL(models.Model):
    url_max = models.URLField(max_length=80, null=True)
    click = models.PositiveIntegerField(default=0)
    url_short = models.CharField(blank=True, max_length=30, unique=True, null=True)
    date_of_create = models.DateTimeField(auto_now_add=True)
    user  = models.ForeignKey(User, null=True, blank=True, related_name='url_user')

urls_short/forms.py
from django import forms
from urls_short.models import URL


class UrlForm(forms.ModelForm):
    class Meta:
        model = URL
        fields = ['url_max', 'url_short']
        labels = { 'url_short': '', 'url_max': ''}
        widgets={'url_max': forms.TextInput(attrs={'placeholder': 'Your URL'}), 
                'url_short': forms.TextInput(attrs={'placeholder': 'Your short URL (optional)'}) }

urls_short/views.py
from urls_short.models import URL
from urls_short.forms import UrlForm
from django.shortcuts import redirect, get_object_or_404, render
import random 
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import string
import datetime
from django.conf import settings
from django.contrib.auth.models import User



def url_generator(size=6, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def update_bd():
    date_del = datetime.date.today() - datetime.timedelta(days=14)
    URL.objects.filter(date_of_create__lte=date_del).delete()
    return URL.objects.all()


def urls_list(request, pk=0):
    urls = update_bd()
    #urls = URL.objects.all()

    if request.method == "POST":
        form = UrlForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            url_new = URL()
            url_new.url_max = data['url_max']

            if data['url_short'] == '':
                url_new.url_short = settings.SITE_URL + "/" + url_generator()
            else:
                url_new.url_short = data['url_short']
            url_new.save()

            return redirect('urls_short:index')
    else:
        form = UrlForm()

    
    if pk != 0:
        app = URL.objects.get(id=pk)  
        app.click += 1
        app.save()
        return redirect(app.url_max)

    paginator = Paginator(urls, 5)
    page = request.GET.get('page')

    try:
        urls = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        urls = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        urls = paginator.page(paginator.num_pages)

    user = request.user

    return render(request, 'index.html', {'urls': urls, 'form': form, 'user':user})



def remove(request, pk):
    user = request.user
    app = URL.objects.get(id=pk)
    if request.method == "POST":
        app.delete()
        return redirect('urls_short:index')
    else:
        return render(request, 'delete.html', {'user': user})



def detail(request, pk):
    url = URL.objects.get(id=pk)
    user = request.user
    return render(request, 'detail.html', {'url': url, 'user':user})



def edit(request, pk):
    url = get_object_or_404(URL, pk=pk)
    user = request.user
    if request.method == "POST":
        form = UrlForm(request.POST, instance=url)
        if form.is_valid():
            url = form.save(commit=False)
            data = form.cleaned_data
            url.url_max = data['url_max']
            url.url_short = data['url_short']
            url.save()
            return redirect('urls_short:index')
    else:
        form = UrlForm(instance=url)
    return render(request, 'edit.html', {'form': form, 'user':user})


def share(request, pk):
    user = request.user
    users = User.objects.exclude(id=user.id)
    if request.method == "GET":
        app = URL.objects.get(id=pk) 
        app.click += 1
        app.save()

    return render(request, 'share.html', {'user':user, 'users': users})

web_url/views.py
from django.shortcuts import render
from django.shortcuts import redirect

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block title %}{% endblock title %}</title>
  <!-- Bootstrap -->


  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>


  <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

  <body>

      <!-- Static navbar -->
      <div class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'urls_short:index' %}">Python URL Shortener</a>
          </div>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#">Admin Panel</a></li>
              <li><a href="#">Sign in as >{% block user %}{% endblock user %}</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </div>


    <div class="jumbotron">
      <div class="container">   
        {% block content %}
        {% endblock content %}   
    </div>
</div>
      <!-- FOOTER -->
      <footer id = "footer_header">
        <p style="text-align: center;">&copy; 2017 Leonova, Inc. &middot; </p>
      </footer>


  <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="static/bootstrap/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/assets/js/ie10-viewport-bug-workaround.js' %}"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="{% static 'js/holder.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>


   </body>
</html>

templates/delete.html
   {% extends "base.html" %}

    {% load staticfiles %}


    {% block title %}URL Delete{% endblock title %}

     {% block user %}{{ user }}{% endblock user %}

{% block content %}

  <form method="post">
    {% csrf_token %}
    {{ form.as_table }}
    <input class= "btn btn-primary btn-lg" type="submit" value="Delete!"/>
  </form>

{% endblock content %}

templates/detail.html
  {% extends "base.html" %}

  {% load staticfiles %}


  {% block title %}{{ url.url_short }}{% endblock title %}

    {% block user %}{{ user }}{% endblock user %}
  
          
  {% block content %}
  <div class="container">
     <div class="table-responsive">
      <table class="table table-striped">
        <tr>
            <th>URL</th>
            <th>Clicks</th>
            <th>Short URL</th>
            <th>Created</th>
            <th>Action</th>
        </tr>
        
        <tr>
           <td><a href="{% url 'urls_short:index' pk=url.id %}">{{ url.url_max }}</a></td>
           <td>{{ url.click }}</td>
           <td><a href="{% url 'urls_short:index' pk=url.id %}">{{ url.url_short }}</a></td>
           <td> {{ url.date_of_create }}</td>
           <td>
            <button><a href="{% url 'urls_short:index' pk=url.id %}" style="text-decoration: none;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Share</a></button>
           <button><a href="{% url 'urls_short:edit' pk=url.id %}" style="text-decoration: none;"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></button>
          </td>
         </tr> 

      </table>  
      </div>
      </div> 

  {% endblock content %}

templates/edit.html
  {% extends "base.html" %}

  {% load staticfiles %}


  {% block title %}{{ url.url_short }}{% endblock title %}

    {% block user %}{{ user }}{% endblock user %}
  
          
  {% block content %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="EDIT"/>
</form>

  {% endblock content %}

templates/index.html
{% extends "base.html" %}

  {% load staticfiles %}


  {% block title %}Shortener URL{% endblock title %}
  
        
  {% block user %}{{ user }}{% endblock user %}

  {% block content %}

 <hr style="border: none; background-color: white; height: 2px;">

<div class="container" id ="form_add">
    <form method="POST" class="post-form">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary btn-lg">Create short URL</button>
    </form>
</div>

  <!-- Default panel contents -->

  <hr style="border: none; background-color: white; height: 2px;">
{% if urls %}
<div class="container">
     <div class="table-responsive">
      <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>URL</th>
            <th>Clicks</th>
            <th>Short URL</th>
            <th>Created</th>
            <th>Action</th>
        </tr>
        {% for i in urls.object_list %}
        <tr>
           <td><a href="{% url 'urls_short:detail' pk=i.id %}">{{ forloop.counter }}</a></td>
           <td><a href="{% url 'urls_short:index' pk=i.id %}">{{ i.url_max }}</a></td>
           <td>{{ i.click }}</td>
           <td><a href="{% url 'urls_short:index' pk=i.id %}">{{ i.url_short }}</a></td>
           <td> {{ i.date_of_create }}</td>
          <td>
          <button><a href="{% url 'urls_short:share' pk=i.id %}" style="text-decoration: none;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Share</a></button>
          <button><a href="{% url 'urls_short:remove' pk=i.id %}" style="text-decoration: none;"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a></button>
          </td>
        </tr> 
    {% endfor %}
      </table>  
      </div>
      </div> 

<hr style="border: none; background-color: white; height: 2px;"/>

<div class="pagination">
    <span class="step-links">
        {% if urls.has_previous %}
            <a href="?page={{ urls.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ urls.number }} of {{ urls.paginator.num_pages }}.
        </span>

        {% if urls.has_next %}
            <a href="?page={{ urls.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>
{% endif %}



{% endblock content %}

templates/share.html
  {% extends "base.html" %}

  {% load staticfiles %}


  {% block title %}{{ url.url_short }}{% endblock title %}
  
  {% block user %}{{ user }}{% endblock user %}
          
  {% block content %}
  <div class="container">
     <div class="table-responsive">
      <table class="table table-striped">
        <tr>
            <th>#</th>
            <th>USER</th>
            <th>Action</th>
        </tr>
        {% for i in users %}
        <tr>
           <td>{{ forloop.counter }}</td>
           <td>{{ i.get_username }}</td>
           <td>
            <button><a href="{% url 'urls_short:index' %}" style="text-decoration: none;"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>Share</a></button>
          </td>
         </tr> 
        {% endfor %}
      </table>  
      </div>
      </div> 

  {% endblock content %}